### ISSUE TITLE
The table options tab can't show more than 5 forms

### ISSUE THREAD

**Issue by ghost** [moshenskyDV/CF7-spreadsheets#1]
Hi,

I'm really impressed with your plugin and it helped me allot thanks so much to you, but I found one major problem which I hope if you can fix it for me.
The issue is that this plugin is unable to show more than 5 contacts 7 forms on the table options tab.

Thanks allot in advance

**Comment by moshenskyDV** [comment]
Thank for you issue. Fixed in [v 2.0.3](https://github.com/moshenskyDV/CF7-spreadsheets/commit/3f288e88a30e8b2a36280e83d41720dd91360a22)

**Comment by ghost** [comment]
Thanks allot, really appreciate that

On Sun, Mar 25, 2018 at 12:21 PM, Moshensky Daniil <notifications@github.com
