### ISSUE TITLE
CF7 version (5.2.1) issue

### ISSUE THREAD

**Issue by manuluyten** [moshenskyDV/CF7-spreadsheets#17]
All,

An issue exist since the latest CF7 version (5.2.1).
I have the following error in my PHP/apache logs:

Got error ‘PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function wpcf7_special_mail_tag(), 3 passed in /var/www/…/wp-content/plugins/cf7-spreadsheets/CF7-spreadsheets.php on line 706 and exactly 4 expected …

CH7 version 5.2.1 changed the wpcf7_special_mail_tag() function following the release notes. This effectively breaks this plugin as of this CF7 version.

Regards

**Comment by moshenskyDV** [comment]
Fixed in [v 2.3.0](https://github.com/moshenskyDV/CF7-spreadsheets/releases/tag/v2.3.0)
