### ISSUE TITLE
wpcf7_* function calls require the 4th param to be a WPCF7_MailTag instance since CF7 5.2.2, but null given

### ISSUE THREAD

**Issue by marazmarci** [moshenskyDV/CF7-spreadsheets#20]
affected lines:
https://github.com/moshenskyDV/CF7-spreadsheets/blob/master/CF7-spreadsheets/CF7-spreadsheets.php#L701
https://github.com/moshenskyDV/CF7-spreadsheets/blob/master/CF7-spreadsheets/CF7-spreadsheets.php#L704
https://github.com/moshenskyDV/CF7-spreadsheets/blob/master/CF7-spreadsheets/CF7-spreadsheets.php#L707
https://github.com/moshenskyDV/CF7-spreadsheets/blob/master/CF7-spreadsheets/CF7-spreadsheets.php#L710

related lines from the source of CF7:
https://github.com/takayukister/contact-form-7/blob/master/includes/special-mail-tags.php#L19
https://github.com/takayukister/contact-form-7/blob/master/includes/special-mail-tags.php#L94
https://github.com/takayukister/contact-form-7/blob/master/includes/special-mail-tags.php#L161
https://github.com/takayukister/contact-form-7/blob/master/includes/special-mail-tags.php#L203

it's a pretty pointless change in CF7...
probably they want to use the value in the future, but currently the param is 100% unused in every one of the 4 functions that are affected ¯\\\_(ツ)\_/¯

idea:
it could be easily fixed by introducing a dummy WPCF7_MailTag instance and passing it instead of nulls.
like this:
```
$dummy_mail_tag = new WPCF7_MailTag('', '', array());
...
} elseif ($defined = wpcf7_special_mail_tag(false, $clear_tag, false, $dummy_mail_tag)) {
```

**Comment by moshenskyDV** [comment]
Hello. I agree with this workaround!
Feel free to create PR (or I will in 1-2 days).

**Comment by marazmarci** [comment]
ok, I will create a PR 🙂
